export const TEACHERS_GET_LIST_RESET = "TEACHERS_GET_LIST_RESET";
export const TEACHERS_GET_LIST_REQUEST = "TEACHERS_GET_LIST_REQUEST";
export const TEACHERS_GET_LIST_SUCCESS = "TEACHERS_GET_LIST_SUCCESS";
export const TEACHERS_GET_LIST_FAIL = "TEACHERS_GET_LIST_FAIL";

export const TEACHERS_ADD_LIST_RESET = "TEACHERS_ADD_LIST_RESET";
export const TEACHERS_ADD_LIST_REQUEST = " TEACHERS_ADD_LIST_REQUEST";
export const TEACHERS_ADD_LIST_SUCCESS = "TEACHERS_ADD_LIST_SUCCESS";
export const TEACHERS_ADD_LIST_FAIL = "TEACHERS_ADD_LIST_FAIL";

export const TEACHERS_DELETE_RESET = "TEACHERS_DELETE_RESET";
export const TEACHERS_DELETE_REQUEST = "TEACHERS_DELETE_REQUEST";
export const TEACHERS_DELETE_SUCCESS = "TEACHERS_DELETE_SUCCESS";
export const TEACHERS_DELETE_FAIL = "TEACHERS_DELETE_FAIL";