export const STUDENT_GET_LIST_RESET = "STUDENT_GET_LIST_RESET";
export const STUDENT_GET_LIST_REQUEST = "STUDENT_GET_LIST_REQUEST";
export const STUDENT_GET_LIST_SUCCESS = "STUDENT_GET_LIST_SUCCESS";
export const STUDENT_GET_LIST_FAIL = "STUDENT_GET_LIST_FAIL";

